- name: Mac OS Setup
  hosts: local
  vars_files:
    - var/default.yml
  tasks:
    - name: Install terminal tools
      ansible.builtin.import_tasks: tasks/terminal.yml
      when: install_terminal_tools
      tags: ["terminal"]
    # - name: Setup zsh
    #   ansible.builtin.import_tasks: tasks/zsh.yml
    #   when: install_terminal_tools
    #   tags: ["zsh"]
