# roles:
#   - name: elliotweiser.osx-command-line-tools
#   - name: geerlingguy.dotfiles

collections:
  - name: community.general # Install Community General Collection
  - name: chocolatey.chocolatey
  - name: kewlfft.aur  # https://galaxy.ansible.com/kewlfft/aur
  - name: ansible.windows
  - name: community.windows
  