---
- name: Get user profile path.
  ansible.windows.win_command: powershell.exe -
  args:
    stdin: echo $HOME
  # TODO: In WSL, it's ansible user not normal user
  register: user_home_path

- name: Get shortcuts.
  ansible.windows.win_find:
    paths:
      - C:\Users\Public\Desktop
      - '{{ user_home_path.stdout | trim }}\Desktop'
      - '{{ user_home_path.stdout | trim }}\OneDrive\Desktop'
    patterns: "*.lnk"
  register: shortcuts

- name: Remove shortcuts from the Desktop.
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ shortcuts.files | unique }}"
  when: shortcuts.files | length > 0
