collections:
  - name: community.general # Install Community General Collection
  - name: chocolatey.chocolatey
  - name: ansible.windows
  - name: community.windows
  - name: kewlfft.aur  # https://galaxy.ansible.com/kewlfft/aur
  